version: "1.0"
stages:
  - "clone"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "theBoEffect/boilerplate"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    image: jch254/docker-node-serverless
    title: Build and Test Service
    working_directory: "${{clone}}"
    commands:
      - yarn
      - yarn test
